# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20170316_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bindhosttouser',
            options={'verbose_name': '主机-用户-绑定关系', 'verbose_name_plural': '主机-用户-绑定关系'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机列表', 'verbose_name_plural': '主机列表'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='hostuser',
            options={'verbose_name': '远程主机用户', 'verbose_name_plural': '远程主机用户'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': 'IDC', 'verbose_name_plural': 'IDC'},
        ),
    ]
