# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20170319_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('mutli_cmd', 'CMD'), ('file_send', '批量发送文件'), ('file_get', '批量下载文件')], max_length=50)),
                ('files_dir', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件上传临时目录')),
                ('cmd', models.TextField()),
                ('expire_time', models.IntegerField(default=30)),
                ('task_pid', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('hosts', models.ManyToManyField(to='hosts.BindHostToUser')),
            ],
            options={
                'verbose_name': '批量任务',
                'verbose_name_plural': '批量任务',
            },
        ),
        migrations.CreateModel(
            name='TaskLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_log', models.TextField()),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('bind_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.BindHostToUser')),
                ('child_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.TaskLog')),
            ],
            options={
                'verbose_name': '批量任务日志',
                'verbose_name_plural': '批量任务日志',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '登录用户信息', 'verbose_name_plural': '登录用户信息'},
        ),
        migrations.AddField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
